generatorName: go
inputSpec: https://api.ttx.gg/swagger/v1/swagger.json
outputDir: .
packageName: gottx
packageVersion: 1.0.0
projectName: gottx
gitHost: github.com
gitUserId: ttxdev
gitRepoId: gottx
enumClassPrefix: true
withGoMod: true
openapiNormalizer:
  SET_TAGS_FOR_ALL_OPERATIONS: TTX
