/*
TTX.Api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gottx

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ModelId type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelId{}

// ModelId struct for ModelId
type ModelId struct {
	Value int32 `json:"value"`
}

type _ModelId ModelId

// NewModelId instantiates a new ModelId object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelId(value int32) *ModelId {
	this := ModelId{}
	this.Value = value
	return &this
}

// NewModelIdWithDefaults instantiates a new ModelId object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelIdWithDefaults() *ModelId {
	this := ModelId{}
	return &this
}

// GetValue returns the Value field value
func (o *ModelId) GetValue() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *ModelId) GetValueOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *ModelId) SetValue(v int32) {
	o.Value = v
}

func (o ModelId) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelId) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *ModelId) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varModelId := _ModelId{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varModelId)

	if err != nil {
		return err
	}

	*o = ModelId(varModelId)

	return err
}

type NullableModelId struct {
	value *ModelId
	isSet bool
}

func (v NullableModelId) Get() *ModelId {
	return v.value
}

func (v *NullableModelId) Set(val *ModelId) {
	v.value = val
	v.isSet = true
}

func (v NullableModelId) IsSet() bool {
	return v.isSet
}

func (v *NullableModelId) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelId(val *ModelId) *NullableModelId {
	return &NullableModelId{value: val, isSet: true}
}

func (v NullableModelId) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelId) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


