/*
TTX.Api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gottx

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TwitchUserDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TwitchUserDto{}

// TwitchUserDto struct for TwitchUserDto
type TwitchUserDto struct {
	Id string `json:"id"`
	DisplayName string `json:"display_name"`
	Login string `json:"login"`
	AvatarUrl string `json:"avatar_url"`
}

type _TwitchUserDto TwitchUserDto

// NewTwitchUserDto instantiates a new TwitchUserDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTwitchUserDto(id string, displayName string, login string, avatarUrl string) *TwitchUserDto {
	this := TwitchUserDto{}
	this.Id = id
	this.DisplayName = displayName
	this.Login = login
	this.AvatarUrl = avatarUrl
	return &this
}

// NewTwitchUserDtoWithDefaults instantiates a new TwitchUserDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTwitchUserDtoWithDefaults() *TwitchUserDto {
	this := TwitchUserDto{}
	return &this
}

// GetId returns the Id field value
func (o *TwitchUserDto) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *TwitchUserDto) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *TwitchUserDto) SetId(v string) {
	o.Id = v
}

// GetDisplayName returns the DisplayName field value
func (o *TwitchUserDto) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *TwitchUserDto) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *TwitchUserDto) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetLogin returns the Login field value
func (o *TwitchUserDto) GetLogin() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Login
}

// GetLoginOk returns a tuple with the Login field value
// and a boolean to check if the value has been set.
func (o *TwitchUserDto) GetLoginOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Login, true
}

// SetLogin sets field value
func (o *TwitchUserDto) SetLogin(v string) {
	o.Login = v
}

// GetAvatarUrl returns the AvatarUrl field value
func (o *TwitchUserDto) GetAvatarUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AvatarUrl
}

// GetAvatarUrlOk returns a tuple with the AvatarUrl field value
// and a boolean to check if the value has been set.
func (o *TwitchUserDto) GetAvatarUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AvatarUrl, true
}

// SetAvatarUrl sets field value
func (o *TwitchUserDto) SetAvatarUrl(v string) {
	o.AvatarUrl = v
}

func (o TwitchUserDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TwitchUserDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["display_name"] = o.DisplayName
	toSerialize["login"] = o.Login
	toSerialize["avatar_url"] = o.AvatarUrl
	return toSerialize, nil
}

func (o *TwitchUserDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"display_name",
		"login",
		"avatar_url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTwitchUserDto := _TwitchUserDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTwitchUserDto)

	if err != nil {
		return err
	}

	*o = TwitchUserDto(varTwitchUserDto)

	return err
}

type NullableTwitchUserDto struct {
	value *TwitchUserDto
	isSet bool
}

func (v NullableTwitchUserDto) Get() *TwitchUserDto {
	return v.value
}

func (v *NullableTwitchUserDto) Set(val *TwitchUserDto) {
	v.value = val
	v.isSet = true
}

func (v NullableTwitchUserDto) IsSet() bool {
	return v.isSet
}

func (v *NullableTwitchUserDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTwitchUserDto(val *TwitchUserDto) *NullableTwitchUserDto {
	return &NullableTwitchUserDto{value: val, isSet: true}
}

func (v NullableTwitchUserDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTwitchUserDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


