/*
TTX.Api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gottx

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreatorPartialDtoPaginationDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreatorPartialDtoPaginationDto{}

// CreatorPartialDtoPaginationDto struct for CreatorPartialDtoPaginationDto
type CreatorPartialDtoPaginationDto struct {
	Data []CreatorPartialDto `json:"data"`
	Total int32 `json:"total"`
}

type _CreatorPartialDtoPaginationDto CreatorPartialDtoPaginationDto

// NewCreatorPartialDtoPaginationDto instantiates a new CreatorPartialDtoPaginationDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatorPartialDtoPaginationDto(data []CreatorPartialDto, total int32) *CreatorPartialDtoPaginationDto {
	this := CreatorPartialDtoPaginationDto{}
	this.Data = data
	this.Total = total
	return &this
}

// NewCreatorPartialDtoPaginationDtoWithDefaults instantiates a new CreatorPartialDtoPaginationDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatorPartialDtoPaginationDtoWithDefaults() *CreatorPartialDtoPaginationDto {
	this := CreatorPartialDtoPaginationDto{}
	return &this
}

// GetData returns the Data field value
func (o *CreatorPartialDtoPaginationDto) GetData() []CreatorPartialDto {
	if o == nil {
		var ret []CreatorPartialDto
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CreatorPartialDtoPaginationDto) GetDataOk() ([]CreatorPartialDto, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *CreatorPartialDtoPaginationDto) SetData(v []CreatorPartialDto) {
	o.Data = v
}

// GetTotal returns the Total field value
func (o *CreatorPartialDtoPaginationDto) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *CreatorPartialDtoPaginationDto) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *CreatorPartialDtoPaginationDto) SetTotal(v int32) {
	o.Total = v
}

func (o CreatorPartialDtoPaginationDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreatorPartialDtoPaginationDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["total"] = o.Total
	return toSerialize, nil
}

func (o *CreatorPartialDtoPaginationDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"total",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreatorPartialDtoPaginationDto := _CreatorPartialDtoPaginationDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreatorPartialDtoPaginationDto)

	if err != nil {
		return err
	}

	*o = CreatorPartialDtoPaginationDto(varCreatorPartialDtoPaginationDto)

	return err
}

type NullableCreatorPartialDtoPaginationDto struct {
	value *CreatorPartialDtoPaginationDto
	isSet bool
}

func (v NullableCreatorPartialDtoPaginationDto) Get() *CreatorPartialDtoPaginationDto {
	return v.value
}

func (v *NullableCreatorPartialDtoPaginationDto) Set(val *CreatorPartialDtoPaginationDto) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatorPartialDtoPaginationDto) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatorPartialDtoPaginationDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatorPartialDtoPaginationDto(val *CreatorPartialDtoPaginationDto) *NullableCreatorPartialDtoPaginationDto {
	return &NullableCreatorPartialDtoPaginationDto{value: val, isSet: true}
}

func (v NullableCreatorPartialDtoPaginationDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatorPartialDtoPaginationDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


