/*
TTX.Api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gottx

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LinkDiscordTwitchDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LinkDiscordTwitchDto{}

// LinkDiscordTwitchDto struct for LinkDiscordTwitchDto
type LinkDiscordTwitchDto struct {
	AccessToken string `json:"access_token"`
	TwitchId string `json:"twitch_id"`
}

type _LinkDiscordTwitchDto LinkDiscordTwitchDto

// NewLinkDiscordTwitchDto instantiates a new LinkDiscordTwitchDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLinkDiscordTwitchDto(accessToken string, twitchId string) *LinkDiscordTwitchDto {
	this := LinkDiscordTwitchDto{}
	this.AccessToken = accessToken
	this.TwitchId = twitchId
	return &this
}

// NewLinkDiscordTwitchDtoWithDefaults instantiates a new LinkDiscordTwitchDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLinkDiscordTwitchDtoWithDefaults() *LinkDiscordTwitchDto {
	this := LinkDiscordTwitchDto{}
	return &this
}

// GetAccessToken returns the AccessToken field value
func (o *LinkDiscordTwitchDto) GetAccessToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccessToken
}

// GetAccessTokenOk returns a tuple with the AccessToken field value
// and a boolean to check if the value has been set.
func (o *LinkDiscordTwitchDto) GetAccessTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessToken, true
}

// SetAccessToken sets field value
func (o *LinkDiscordTwitchDto) SetAccessToken(v string) {
	o.AccessToken = v
}

// GetTwitchId returns the TwitchId field value
func (o *LinkDiscordTwitchDto) GetTwitchId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TwitchId
}

// GetTwitchIdOk returns a tuple with the TwitchId field value
// and a boolean to check if the value has been set.
func (o *LinkDiscordTwitchDto) GetTwitchIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TwitchId, true
}

// SetTwitchId sets field value
func (o *LinkDiscordTwitchDto) SetTwitchId(v string) {
	o.TwitchId = v
}

func (o LinkDiscordTwitchDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LinkDiscordTwitchDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["access_token"] = o.AccessToken
	toSerialize["twitch_id"] = o.TwitchId
	return toSerialize, nil
}

func (o *LinkDiscordTwitchDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"access_token",
		"twitch_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLinkDiscordTwitchDto := _LinkDiscordTwitchDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLinkDiscordTwitchDto)

	if err != nil {
		return err
	}

	*o = LinkDiscordTwitchDto(varLinkDiscordTwitchDto)

	return err
}

type NullableLinkDiscordTwitchDto struct {
	value *LinkDiscordTwitchDto
	isSet bool
}

func (v NullableLinkDiscordTwitchDto) Get() *LinkDiscordTwitchDto {
	return v.value
}

func (v *NullableLinkDiscordTwitchDto) Set(val *LinkDiscordTwitchDto) {
	v.value = val
	v.isSet = true
}

func (v NullableLinkDiscordTwitchDto) IsSet() bool {
	return v.isSet
}

func (v *NullableLinkDiscordTwitchDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLinkDiscordTwitchDto(val *LinkDiscordTwitchDto) *NullableLinkDiscordTwitchDto {
	return &NullableLinkDiscordTwitchDto{value: val, isSet: true}
}

func (v NullableLinkDiscordTwitchDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLinkDiscordTwitchDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


