/*
TTX.Api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gottx

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TokenDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TokenDto{}

// TokenDto struct for TokenDto
type TokenDto struct {
	AccessToken string `json:"access_token"`
}

type _TokenDto TokenDto

// NewTokenDto instantiates a new TokenDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTokenDto(accessToken string) *TokenDto {
	this := TokenDto{}
	this.AccessToken = accessToken
	return &this
}

// NewTokenDtoWithDefaults instantiates a new TokenDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokenDtoWithDefaults() *TokenDto {
	this := TokenDto{}
	return &this
}

// GetAccessToken returns the AccessToken field value
func (o *TokenDto) GetAccessToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccessToken
}

// GetAccessTokenOk returns a tuple with the AccessToken field value
// and a boolean to check if the value has been set.
func (o *TokenDto) GetAccessTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessToken, true
}

// SetAccessToken sets field value
func (o *TokenDto) SetAccessToken(v string) {
	o.AccessToken = v
}

func (o TokenDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TokenDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["access_token"] = o.AccessToken
	return toSerialize, nil
}

func (o *TokenDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"access_token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTokenDto := _TokenDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTokenDto)

	if err != nil {
		return err
	}

	*o = TokenDto(varTokenDto)

	return err
}

type NullableTokenDto struct {
	value *TokenDto
	isSet bool
}

func (v NullableTokenDto) Get() *TokenDto {
	return v.value
}

func (v *NullableTokenDto) Set(val *TokenDto) {
	v.value = val
	v.isSet = true
}

func (v NullableTokenDto) IsSet() bool {
	return v.isSet
}

func (v *NullableTokenDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokenDto(val *TokenDto) *NullableTokenDto {
	return &NullableTokenDto{value: val, isSet: true}
}

func (v NullableTokenDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokenDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


