/*
TTX.Api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gottx

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PlayerShareDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlayerShareDto{}

// PlayerShareDto struct for PlayerShareDto
type PlayerShareDto struct {
	Creator CreatorPartialDto `json:"creator"`
	Quantity int32 `json:"quantity"`
}

type _PlayerShareDto PlayerShareDto

// NewPlayerShareDto instantiates a new PlayerShareDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlayerShareDto(creator CreatorPartialDto, quantity int32) *PlayerShareDto {
	this := PlayerShareDto{}
	this.Creator = creator
	this.Quantity = quantity
	return &this
}

// NewPlayerShareDtoWithDefaults instantiates a new PlayerShareDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlayerShareDtoWithDefaults() *PlayerShareDto {
	this := PlayerShareDto{}
	return &this
}

// GetCreator returns the Creator field value
func (o *PlayerShareDto) GetCreator() CreatorPartialDto {
	if o == nil {
		var ret CreatorPartialDto
		return ret
	}

	return o.Creator
}

// GetCreatorOk returns a tuple with the Creator field value
// and a boolean to check if the value has been set.
func (o *PlayerShareDto) GetCreatorOk() (*CreatorPartialDto, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Creator, true
}

// SetCreator sets field value
func (o *PlayerShareDto) SetCreator(v CreatorPartialDto) {
	o.Creator = v
}

// GetQuantity returns the Quantity field value
func (o *PlayerShareDto) GetQuantity() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value
// and a boolean to check if the value has been set.
func (o *PlayerShareDto) GetQuantityOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Quantity, true
}

// SetQuantity sets field value
func (o *PlayerShareDto) SetQuantity(v int32) {
	o.Quantity = v
}

func (o PlayerShareDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlayerShareDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["creator"] = o.Creator
	toSerialize["quantity"] = o.Quantity
	return toSerialize, nil
}

func (o *PlayerShareDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"creator",
		"quantity",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPlayerShareDto := _PlayerShareDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPlayerShareDto)

	if err != nil {
		return err
	}

	*o = PlayerShareDto(varPlayerShareDto)

	return err
}

type NullablePlayerShareDto struct {
	value *PlayerShareDto
	isSet bool
}

func (v NullablePlayerShareDto) Get() *PlayerShareDto {
	return v.value
}

func (v *NullablePlayerShareDto) Set(val *PlayerShareDto) {
	v.value = val
	v.isSet = true
}

func (v NullablePlayerShareDto) IsSet() bool {
	return v.isSet
}

func (v *NullablePlayerShareDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlayerShareDto(val *PlayerShareDto) *NullablePlayerShareDto {
	return &NullablePlayerShareDto{value: val, isSet: true}
}

func (v NullablePlayerShareDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlayerShareDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


