/*
TTX.Api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gottx

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the PlayerPartialDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlayerPartialDto{}

// PlayerPartialDto struct for PlayerPartialDto
type PlayerPartialDto struct {
	Id int32 `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Name string `json:"name"`
	Slug string `json:"slug"`
	TwitchId string `json:"twitch_id"`
	Url string `json:"url"`
	AvatarUrl string `json:"avatar_url"`
	Credits int64 `json:"credits"`
	Portfolio int64 `json:"portfolio"`
	Value int64 `json:"value"`
	Type PlayerType `json:"type"`
}

type _PlayerPartialDto PlayerPartialDto

// NewPlayerPartialDto instantiates a new PlayerPartialDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlayerPartialDto(id int32, createdAt time.Time, updatedAt time.Time, name string, slug string, twitchId string, url string, avatarUrl string, credits int64, portfolio int64, value int64, type_ PlayerType) *PlayerPartialDto {
	this := PlayerPartialDto{}
	this.Id = id
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	this.Name = name
	this.Slug = slug
	this.TwitchId = twitchId
	this.Url = url
	this.AvatarUrl = avatarUrl
	this.Credits = credits
	this.Portfolio = portfolio
	this.Value = value
	this.Type = type_
	return &this
}

// NewPlayerPartialDtoWithDefaults instantiates a new PlayerPartialDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlayerPartialDtoWithDefaults() *PlayerPartialDto {
	this := PlayerPartialDto{}
	return &this
}

// GetId returns the Id field value
func (o *PlayerPartialDto) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PlayerPartialDto) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PlayerPartialDto) SetId(v int32) {
	o.Id = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *PlayerPartialDto) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *PlayerPartialDto) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *PlayerPartialDto) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *PlayerPartialDto) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *PlayerPartialDto) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *PlayerPartialDto) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetName returns the Name field value
func (o *PlayerPartialDto) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PlayerPartialDto) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PlayerPartialDto) SetName(v string) {
	o.Name = v
}

// GetSlug returns the Slug field value
func (o *PlayerPartialDto) GetSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Slug
}

// GetSlugOk returns a tuple with the Slug field value
// and a boolean to check if the value has been set.
func (o *PlayerPartialDto) GetSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Slug, true
}

// SetSlug sets field value
func (o *PlayerPartialDto) SetSlug(v string) {
	o.Slug = v
}

// GetTwitchId returns the TwitchId field value
func (o *PlayerPartialDto) GetTwitchId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TwitchId
}

// GetTwitchIdOk returns a tuple with the TwitchId field value
// and a boolean to check if the value has been set.
func (o *PlayerPartialDto) GetTwitchIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TwitchId, true
}

// SetTwitchId sets field value
func (o *PlayerPartialDto) SetTwitchId(v string) {
	o.TwitchId = v
}

// GetUrl returns the Url field value
func (o *PlayerPartialDto) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *PlayerPartialDto) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *PlayerPartialDto) SetUrl(v string) {
	o.Url = v
}

// GetAvatarUrl returns the AvatarUrl field value
func (o *PlayerPartialDto) GetAvatarUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AvatarUrl
}

// GetAvatarUrlOk returns a tuple with the AvatarUrl field value
// and a boolean to check if the value has been set.
func (o *PlayerPartialDto) GetAvatarUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AvatarUrl, true
}

// SetAvatarUrl sets field value
func (o *PlayerPartialDto) SetAvatarUrl(v string) {
	o.AvatarUrl = v
}

// GetCredits returns the Credits field value
func (o *PlayerPartialDto) GetCredits() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Credits
}

// GetCreditsOk returns a tuple with the Credits field value
// and a boolean to check if the value has been set.
func (o *PlayerPartialDto) GetCreditsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Credits, true
}

// SetCredits sets field value
func (o *PlayerPartialDto) SetCredits(v int64) {
	o.Credits = v
}

// GetPortfolio returns the Portfolio field value
func (o *PlayerPartialDto) GetPortfolio() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Portfolio
}

// GetPortfolioOk returns a tuple with the Portfolio field value
// and a boolean to check if the value has been set.
func (o *PlayerPartialDto) GetPortfolioOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Portfolio, true
}

// SetPortfolio sets field value
func (o *PlayerPartialDto) SetPortfolio(v int64) {
	o.Portfolio = v
}

// GetValue returns the Value field value
func (o *PlayerPartialDto) GetValue() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *PlayerPartialDto) GetValueOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *PlayerPartialDto) SetValue(v int64) {
	o.Value = v
}

// GetType returns the Type field value
func (o *PlayerPartialDto) GetType() PlayerType {
	if o == nil {
		var ret PlayerType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *PlayerPartialDto) GetTypeOk() (*PlayerType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *PlayerPartialDto) SetType(v PlayerType) {
	o.Type = v
}

func (o PlayerPartialDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlayerPartialDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	toSerialize["name"] = o.Name
	toSerialize["slug"] = o.Slug
	toSerialize["twitch_id"] = o.TwitchId
	toSerialize["url"] = o.Url
	toSerialize["avatar_url"] = o.AvatarUrl
	toSerialize["credits"] = o.Credits
	toSerialize["portfolio"] = o.Portfolio
	toSerialize["value"] = o.Value
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *PlayerPartialDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"created_at",
		"updated_at",
		"name",
		"slug",
		"twitch_id",
		"url",
		"avatar_url",
		"credits",
		"portfolio",
		"value",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPlayerPartialDto := _PlayerPartialDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPlayerPartialDto)

	if err != nil {
		return err
	}

	*o = PlayerPartialDto(varPlayerPartialDto)

	return err
}

type NullablePlayerPartialDto struct {
	value *PlayerPartialDto
	isSet bool
}

func (v NullablePlayerPartialDto) Get() *PlayerPartialDto {
	return v.value
}

func (v *NullablePlayerPartialDto) Set(val *PlayerPartialDto) {
	v.value = val
	v.isSet = true
}

func (v NullablePlayerPartialDto) IsSet() bool {
	return v.isSet
}

func (v *NullablePlayerPartialDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlayerPartialDto(val *PlayerPartialDto) *NullablePlayerPartialDto {
	return &NullablePlayerPartialDto{value: val, isSet: true}
}

func (v NullablePlayerPartialDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlayerPartialDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


